apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: panda-stg1
namePrefix: panda-stg1-
commonLabels:
  env: stg1

patchesStrategicMerge:
  - panda.yml

images:
  - name: sontbv/panda
  - newTag: latest

bases:
  - ../../base
